pure_pursuit_odom:
  ros__parameters:
    global_frame: "odom"
    robot_frame: "base_link"
    action_name: "follow_path_odom"

    max_linear_vel: 0.3
    accel_limit: 0.1

    min_lookahead_dist: 0.1
    lookahead_gain: 0.1

    max_angular_vel: 0.6
    kp_yaw: 2.0

    goal_tolerance: 0.005
    yaw_tolerance: 0.02

    v_floor: 0.2
    v_min_push: 0.02

    min_vel_enforce_dist: 0.3

    control_frequency: 50.0

    # --- その他設定（必要に応じてプログラム側で追加・利用可能） ---
    use_sim_time: False
